info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

logging:
  level:
     org:
       springframework:
         security: DEBUG
